version: 2

jobs:
  requirements:
    docker:
      - image: web3f/ansible:v0.0.3

    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt

  benchmark-1:
    docker:
      - image: web3f/ansible:v0.0.3
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          command: |
            ansible-playbook --extra-vars "machine_type=e2-micro" w3f/substrate-benchmarks/benchmarks.yaml
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-e2-micro


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - requirements:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - benchmark-1:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - requirements
