version: 2

jobs:
  requirements:
    docker:
      - image: web3f/ansible:v0.0.4

    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt

  benchmark-e2-micro:
    docker:
      - image: web3f/ansible:v0.0.4
      
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          name: benchmark e2-micro
          command: ansible-playbook --extra-vars "machine_type=e2-micro" w3f/substrate-benchmarks/benchmarks.yaml
          no_output_timeout: 90m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-e2-micro

  benchmark-e2-small:
    docker:
      - image: web3f/ansible:v0.0.4
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          name: benchmark e2-small
          command: ansible-playbook --extra-vars "machine_type=e2-small" w3f/substrate-benchmarks/benchmarks.yaml
          no_output_timeout: 90m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-e2-small

  benchmark-e2-medium:
    docker:
      - image: web3f/ansible:v0.0.4
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          name: benchmark e2-medium
          command: ansible-playbook --extra-vars "machine_type=e2-medium" w3f/substrate-benchmarks/benchmarks.yaml
          no_output_timeout: 90m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-e2-medium

  benchmark-n1-standard-1:
    docker:
      - image: web3f/ansible:v0.0.4
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          name: benchmark n1-standard-1
          command: ansible-playbook --extra-vars "machine_type=n1-standard-1" w3f/substrate-benchmarks/benchmarks.yaml
          no_output_timeout: 90m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-n1-standard-1

  benchmark-n1-standard-2:
    docker:
      - image: web3f/ansible:v0.0.4
    steps:
      - checkout
      - run:
          command: |
            pip install -r w3f/substrate-benchmarks/requirements.txt
      - run:
          name: benchmark n1-standard-2
          command: ansible-playbook --extra-vars "machine_type=n1-standard-2" w3f/substrate-benchmarks/benchmarks.yaml
          no_output_timeout: 90m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - store_artifacts:
          path: w3f/substrate-benchmarks/results
          destination: results-artifact-n1-standard-2

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - requirements:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - benchmark-e2-micro:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - requirements
