---
- name: Configure
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Set provider
    set_fact:
      provider: gcp

- name: Provision
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: CREATE
      machine_type: "n1-standard-1"
  - name: Add key to ssh-agent
    shell: ssh-add id_ed25519
  - git:
      repo: 'https://github.com/w3f/polkadot-module-benchmarking.git'
      dest: roles/substrate-benchmarks

- name: Run Benchmark
  hosts: substrate-benchmarks
  gather_facts: yes
  tasks:
  - ping:
  roles:
    - role: substrate-benchmarks
      vars:
        benchmarking_binary_url: 'https://github.com/lamafab/substrate-graph-benchmarks/releases/download/v0.1.0/substrate'
        benchmark_steps: 1
        benchmark_repeat: 1

- name: Clean
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: destroy instance
    include_role:
      name: "{{ provider }}"
    vars:
      stage: DESTROY
