---
- name: provision
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    provider: gcp
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: CREATE
  - name: Run
  - name: Clear
    include_role:
      name: "{{ provider }}"
    vars:
      stage: DESTROY
