---
- name: provision
  hosts: localhost
  gather_facts: yes
  vars:
   set_region: europe-west3
  roles:
     - create-gcp

- name: run benchmark
  hosts: dynamic-inventory.gcp.yml
  gather_facts: yes
  vars:
   set_region: europe-west3

- name: destroy
  hosts: localhost
  gather_facts: yes
  vars:
   set_region: europe-west3
  roles:
     - destroy-gcp
