---
- name: configure
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Set provider
    set_fact:
      provider: gcp

- name: provision
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: CREATE
      machine_type: "e2-standard-2"

- name: run benchmark
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Printout target
    debug:
      msg: "{{ target }}"


- name: provision
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: DESTROY
