---
- name: provision
  hosts: localhost
  gather_facts: yes
  roles:
     - create-gcp
  vars:
   set_region: europe-west3

- name: run benchmark
# ansible-inventory --list -i dynamic-inventory.gcp.yml
  hosts: dynamic-inventory.gcp.yml
  # hosts: "{{ target | default('ubuntu_18_04') }}"
  gather_facts: yes
  roles:
     - substrate-benchmarks
  vars:
   set_region: europe-west3

- name: destroy
  hosts: localhost
  gather_facts: yes
  roles:
     - destroy-gcp
  vars:
   set_region: europe-west3
