---
- name: Configure
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Set provider
    set_fact:
      provider: gcp

- name: Provision
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: CREATE
      remote_user: sa_106627723496398399336
      machine_type: "e2-micro"

- name: Run Benchmark
  hosts: substrate-benchmarks
  gather_facts: yes
  remote_user: sa_106627723496398399336
  tasks:
  - name: Add key to ssh-agent
    shell: ssh-add id_ed25519
    delegate_to: localhost
  - ping:
  roles:
    - role: substrate-benchmarks
      vars:
        set_benchmarking_binary_url: 'https://github.com/lamafab/substrate-graph-benchmarks/releases/download/v0.1.0/substrate'
        set_benchmark_steps: 2
        set_benchmark_repeat: 2

- name: Clean
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: destroy instance
    include_role:
      name: "{{ provider }}"
    vars:
      stage: DESTROY
